version: "3.1"
services:
    www:
        build:
          args:
            - VHOST_CONF_PATH=container/virtual-host/
          context: ./
          dockerfile: Dockerfile
        ports: 
            - "80:80"
        links:
          - db
        volumes:
            - ../backend/:/var/www/backend/
            - ../front/:/var/www/front/
            - ./xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - default
        extra_hosts:
            - "host.docker.internal:192.168.1.35"
    db:
      image: mysql:8.0
      ports:
        - "3306:3306"
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: docker_www_db
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
      volumes:
        - ./dump:/docker-entrypoint-initdb.d
        - ./conf:/etc/mysql/conf.d
        - persistent:/var/lib/mysql
      networks:
        - default
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - db:db
      ports:
        - 8000:80
      environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
volumes:
    persistent:
